In [68]:
import pandas as pd
import scipy as sp
import numpy as np
from context import km3net
from km3net.utils import DATADIR

In [64]:
ids = np.array([np.nan, np.nan, 45, np.nan, 45])
ids

array([nan, nan, 45., nan, 45.])

In [65]:
matrix = np.zeros((len(ids), len(ids)))
matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
for row, row_event in enumerate(ids):
    for col, col_event in enumerate(ids[row+1:]):
        if row_event == col_event:
            matrix[row, col] = 1

In [67]:
matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
df[3:][df.event_id == 45.0]

<ipython-input-47-82e6097a177e>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[3:][df.event_id == 45.0]


event_id
4      45.0

In [69]:
df = pd.read_csv(DATADIR+'/processed/slice-615.csv')
df

pos_x   pos_y    pos_z       time  label  event_id  timeslice
0     48.363 -24.102   83.611  9225002.0      0       NaN        615
1    -37.784  30.774   94.341  9225007.0      0       NaN        615
2    -75.557  -6.893   56.111  9225008.0      0       NaN        615
3    -27.018 -60.655  150.731  9225013.0      0       NaN        615
4     76.914 -77.120  150.789  9225014.0      0       NaN        615
...      ...     ...      ...        ...    ...       ...        ...
8478  50.125  12.122  139.831  9239990.0      0       NaN        615
8479 -74.918  65.066   74.041  9239993.0      0       NaN        615
8480 -94.292  -6.028  103.911  9239996.0      0       NaN        615
8481  11.829  13.744  130.489  9239998.0      0       NaN        615
8482 -26.345 -94.841  103.741  9240000.0      0       NaN        615

[8483 rows x 7 columns]

In [70]:
df = df[['event_id']]
df

event_id
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
8478       NaN
8479       NaN
8480       NaN
8481       NaN
8482       NaN

[8483 rows x 1 columns]

In [103]:
matrix = pd.DataFrame(np.zeros((len(df), len(df))), columns=df.event_id, index=df.event_id)
matrix

event_id  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  \
event_id                                                    ...             
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

event_id  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
event_id                                          
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...       ...  ...  ...  ...  ...  ...  ...  ...  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[8483 rows x 8483 columns]

In [78]:
for col in matrix:
    if ~np.isnan(col):
        matrix.loc[col, col] = 1

In [81]:
matrix.columns.unique()

Float64Index([nan, 2322.0, 1163.0, 2042.0, 2363.0], dtype='float64', name='event_id')

In [96]:
matrix

event_id  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  \
event_id                                                    ...             
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

event_id  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
event_id                                          
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...       ...  ...  ...  ...  ...  ...  ...  ...  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
NaN       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[8483 rows x 8483 columns]

In [101]:
matrix[matrix.eq(1).any(1)]


event_id  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  \
event_id                                                    ...             
2322.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2322.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2322.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2322.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2322.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
2363.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2363.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2363.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2363.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2363.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

event_id  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
event_id                                          
2322.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2322.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2322.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2322.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2322.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...       ...  ...  ...  ...  ...  ...  ...  ...  
2363.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2363.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2363.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2363.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2363.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[1692 rows x 8483 columns]